name: Issue Report
description: Report an issue with the mod
title: '[Issue]'
body:
  - type: input
    id: modVer
    attributes:
      label: Mod version
      description: >
        What version of the mod are you using?

        The version can be found from either the file name or the mods list on
        the main menu
      placeholder: e.g 1.0.8+mc1.16.5
    validations:
      required: true
  - type: input
    id: forgeVer
    attributes:
      label: Forge mod loader version
      description: |
        The version of the forge mod loader that is being used
      placeholder: e.g 37.0.34
  - type: checkboxes
    id: repeatable
    attributes:
      label: Repeatable?
      description: |
        Is the issue you are having repeatable?
      options:
        - label: 'Yes'
          validations:
            required: false
  - type: textarea
    id: logs
    attributes:
      label: Link to logs
      description: Add any link to log files here
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce the issue
      description: |
        Tell us how we can reproduce the issue
        If not repeatable just ignore this
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. Scroll down to ...
        4. See error
  - type: textarea
    id: issueDescription
    attributes:
      label: Description of the issue you are having
      description: |
        A clear description of the issue you are having.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Information
      options:
        - label: I have provided as much information as possible
          validations:
            required: false
  - type: markdown
    attributes:
      value: >-
        This template was generated with [Issue Forms
        Creator](https://www.issue-forms-creator.app/)
